import { BRAND } from "../constants/brand";
import { getLogoWhiteB64, getLogoOrigB64 } from "../constants/logos";
import { formatDate, fmtEventDate, fmtTime } from "./dates";
import { rc, rb, resolveCorporateBlock } from "./ratings";
import { fmtUpside, upsideColor, calcUpside } from "./prices";
import { nl2br } from "./text";

export function generateHTML(s) {
  const B = BRAND;

  // --- existing sections ---

  const macro = s.sections.find(x=>x.key==="macro")?.on ? `<tr><td style="padding:0 32px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:14px;"><tr><td><div style="font-size:11px;font-weight:700;color:#fff;background:${B.blue};text-transform:uppercase;letter-spacing:1.5px;padding:5px 12px;display:inline-block;">Macro / Political</div></td></tr></table>${s.macroBlocks.map(b => `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:16px;border-bottom:1px solid #e4e8ed;padding-bottom:12px;"><tr><td><div style="font-size:12.5px;font-weight:700;color:${B.navy};text-transform:uppercase;letter-spacing:0.8px;margin-bottom:6px;padding-bottom:4px;border-bottom:2px solid ${B.sky};display:inline-block;">${b.title}</div><div style="font-size:13px;line-height:1.55;color:#333;margin-top:4px;">${nl2br(b.body)}</div>${b.lsPick ? `<div style="background:${B.greenBg};border-left:3px solid ${B.green};padding:8px 12px;margin-top:8px;font-size:12.5px;line-height:1.5;color:#2d5a25;"><strong>LS pick:</strong> ${nl2br(b.lsPick)}</div>` : ""}</td></tr></table>`).join("")}</td></tr>` : "";

  const allTickers = s.analysts.flatMap(a => a.coverage.map(c => ({ ticker: c.ticker, rating: c.rating, tp: c.tp, last: c.last||"", analyst: a.name })));

  const trade = s.sections.find(x=>x.key==="tradeIdeas")?.on ? `<tr><td style="padding:0 32px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:14px;"><tr><td><div style="font-size:11px;font-weight:700;color:#fff;background:${B.blue};text-transform:uppercase;letter-spacing:1.5px;padding:5px 12px;display:inline-block;">Trade Ideas</div></td></tr></table><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:14px;"><tr><td><div style="font-size:12.5px;font-weight:700;color:${B.navy};margin-bottom:6px;">Equity — Research Top Picks</div>${s.equityPicks.filter(p=>p.ticker).map(p => { const info = allTickers.find(x => x.ticker === p.ticker); return `<div style="margin-bottom:6px;"><span style="display:inline-block;background:${info ? rc(info.rating) : B.navy};color:#fff;font-size:11px;font-weight:700;padding:4px 10px;border-radius:3px;">${p.ticker}</span>${info ? `<span style="font-size:11px;color:#666;margin-left:6px;">${info.rating} | TP ${info.tp}${info.last ? ` | Last ${info.last}` : ""}${info.tp && info.last ? ` | <span style="color:${upsideColor(info.tp,info.last)};font-weight:700;">${fmtUpside(info.tp,info.last)}</span>` : ""}</span>` : ""}${p.reason ? `<div style="font-size:12px;color:#555;margin-top:2px;margin-left:4px;font-style:italic;">${p.reason}</div>` : ""}</div>`; }).join("")}</td></tr></table><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:16px;border-bottom:1px solid #e4e8ed;padding-bottom:12px;"><tr><td><div style="font-size:12.5px;font-weight:700;color:${B.navy};margin-bottom:6px;">Fixed Income</div>${s.fiIdeas.filter(f=>f.idea).map(f => `<div style="margin-bottom:6px;"><div style="font-size:13px;line-height:1.5;color:#333;">&#9654; <strong>${f.idea}</strong></div>${f.reason ? `<div style="font-size:12px;color:#555;margin-left:18px;font-style:italic;">${f.reason}</div>` : ""}</div>`).join("")}</td></tr></table></td></tr>` : "";

  const flow = s.sections.find(x=>x.key==="flows")?.on ? `<tr><td style="padding:0 32px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:14px;"><tr><td><div style="font-size:11px;font-weight:700;color:#fff;background:${B.blue};text-transform:uppercase;letter-spacing:1.5px;padding:5px 12px;display:inline-block;">LS Trading Desk Flows</div></td></tr></table><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:16px;border-bottom:1px solid #e4e8ed;padding-bottom:12px;"><tr><td width="50%" valign="top" style="padding-right:12px;"><div style="font-size:11px;font-weight:700;color:${B.navy};text-transform:uppercase;margin-bottom:4px;">Equities</div><div style="font-size:13px;line-height:1.55;color:#333;"><span style="color:#27864a;font-weight:600;">▲ Buyer</span> ${s.eqBuyer}<br><span style="color:#c0392b;font-weight:600;">▼ Seller</span> ${s.eqSeller}</div></td><td width="50%" valign="top" style="padding-left:12px;border-left:1px solid #e4e8ed;"><div style="font-size:11px;font-weight:700;color:${B.navy};text-transform:uppercase;margin-bottom:4px;">Fixed Income</div><div style="font-size:13px;line-height:1.55;color:#333;"><span style="color:#27864a;font-weight:600;">▲ Net buyer</span> ${s.fiBuyer}<br><span style="color:#c0392b;font-weight:600;">▼ Net seller</span> ${s.fiSeller}</div></td></tr></table></td></tr>` : "";

  const mEst = s.sections.find(x=>x.key==="macroEstimates")?.on ? `<tr><td style="padding:0 32px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:14px;"><tr><td><div style="font-size:11px;font-weight:700;color:#fff;background:${B.blue};text-transform:uppercase;letter-spacing:1.5px;padding:5px 12px;display:inline-block;">Macro Estimates</div></td></tr></table><div style="font-size:10px;color:#666;margin-bottom:6px;">Source: ${s.macroSource}</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border:1px solid #dde3ea;margin-bottom:16px;"><tr style="background:${B.navy};"><td style="padding:6px 10px;font-size:11px;font-weight:700;color:#fff;width:40%;"></td>${s.macroCols.map(c => `<td style="padding:6px 10px;font-size:11px;font-weight:700;color:#fff;text-align:center;">${c}</td>`).join("")}</tr>${s.macroRows.map((r,i) => `<tr style="background:${i%2===0?"#f8fafc":"#fff"};"><td style="padding:6px 10px;font-size:12px;font-weight:600;color:#333;border-right:1px solid #e4e8ed;border-bottom:1px solid #e4e8ed;">${r.label}</td>${s.macroCols.map(c => `<td style="padding:6px 10px;font-size:12px;color:#333;text-align:center;border-right:1px solid #e4e8ed;border-bottom:1px solid #e4e8ed;">${r.vals[c]||""}</td>`).join("")}</tr>`).join("")}</table></td></tr>` : "";

  const corp = s.sections.find(x=>x.key==="corporate")?.on ? `<tr><td style="padding:0 32px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:14px;"><tr><td><div style="font-size:11px;font-weight:700;color:#fff;background:${B.blue};text-transform:uppercase;letter-spacing:1.5px;padding:5px 12px;display:inline-block;">Corporate</div></td></tr></table>${s.corpBlocks.map(c => { const r = resolveCorporateBlock(c, s.analysts); return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:16px;border-bottom:1px solid #e4e8ed;padding-bottom:12px;"><tr><td><div style="font-size:12.5px;font-weight:700;color:${B.navy};text-transform:uppercase;letter-spacing:0.8px;margin-bottom:4px;">${r.tickers.join(" / ")} — ${r.headline}</div>${r.covs.filter(cv=>cv.ticker).map(cv => `<div style="margin-bottom:3px;"><span style="display:inline-block;background:${rb(cv.rating)};color:${rc(cv.rating)};font-size:10px;font-weight:700;padding:2px 6px;border-radius:3px;">${cv.ticker} ${cv.rating}</span><span style="font-size:11px;color:#333;margin-left:4px;">TP ${cv.tp}${cv.last ? ` | Last ${cv.last}` : ""}${cv.tp && cv.last ? ` | <span style="color:${upsideColor(cv.tp,cv.last)};font-weight:700;">${fmtUpside(cv.tp,cv.last)}</span>` : ""}</span></div>`).join("")}<div style="font-size:11px;color:#666;margin-bottom:6px;font-style:italic;">${r.analyst}</div><div style="font-size:13px;line-height:1.55;color:#333;">${nl2br(r.body)}</div>${r.link ? `<div style="margin-top:6px;"><a href="${r.link}" style="font-size:12px;color:${B.blue};">Full LS report →</a></div>` : ""}</td></tr></table>`; }).join("")}</td></tr>` : "";

  const research = s.sections.find(x=>x.key==="research")?.on && s.researchReports?.length ? `<tr><td style="padding:0 32px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:14px;"><tr><td><div style="font-size:11px;font-weight:700;color:#fff;background:${B.blue};text-transform:uppercase;letter-spacing:1.5px;padding:5px 12px;display:inline-block;">Research Reports</div></td></tr></table>${(s.researchReports||[]).filter(r=>r.title).map(r => `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:14px;border-bottom:1px solid #e4e8ed;padding-bottom:10px;"><tr><td><div style="margin-bottom:4px;"><span style="display:inline-block;background:${r.type==="Macro"?"#e3f2fd":r.type==="Weekly"?"#fce4ec":r.type==="Strategy"?"#f3e5f5":"#e8eaf6"};color:${r.type==="Macro"?"#1565c0":r.type==="Weekly"?"#c62828":r.type==="Strategy"?"#6a1b9a":"#283593"};font-size:10px;font-weight:700;padding:2px 8px;border-radius:3px;text-transform:uppercase;">${r.type}</span></div><div style="font-size:12.5px;font-weight:700;color:${B.navy};margin-bottom:3px;">${r.title}</div>${r.author ? `<div style="font-size:11px;color:#666;font-style:italic;margin-bottom:4px;">${r.author}</div>` : ""}${r.body ? `<div style="font-size:13px;line-height:1.5;color:#333;margin-bottom:4px;">${nl2br(r.body)}</div>` : ""}${r.link ? `<a href="${r.link}" style="font-size:12px;color:${B.blue};">Read report →</a>` : ""}</td></tr></table>`).join("")}</td></tr>` : "";

  // --- new sections ---

  const topMoversGainers = s.topMovers?.gainers?.filter(m=>m.ticker) || [];
  const topMoversLosers = s.topMovers?.losers?.filter(m=>m.ticker) || [];
  const topMovers = s.sections.find(x=>x.key==="topMovers")?.on && (topMoversGainers.length || topMoversLosers.length) ? `<tr><td style="padding:0 32px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:14px;"><tr><td><div style="font-size:11px;font-weight:700;color:#fff;background:${B.blue};text-transform:uppercase;letter-spacing:1.5px;padding:5px 12px;display:inline-block;">Top Movers</div></td></tr></table><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border:1px solid #dde3ea;margin-bottom:16px;"><tr style="background:${B.navy};"><td style="padding:6px 10px;font-size:11px;font-weight:700;color:#fff;">Ticker</td><td style="padding:6px 10px;font-size:11px;font-weight:700;color:#fff;text-align:right;">% Chg</td><td style="padding:6px 10px;font-size:11px;font-weight:700;color:#fff;">Comment</td></tr>${topMoversGainers.map((m,i) => `<tr style="background:${i%2===0?"#f8fafc":"#fff"};"><td style="padding:6px 10px;font-size:12px;font-weight:600;color:#333;border-bottom:1px solid #e4e8ed;">${m.ticker}</td><td style="padding:6px 10px;font-size:12px;font-weight:700;color:#27864a;text-align:right;border-bottom:1px solid #e4e8ed;">+${m.chgPct}%</td><td style="padding:6px 10px;font-size:12px;color:#555;border-bottom:1px solid #e4e8ed;">${m.comment||""}</td></tr>`).join("")}${topMoversLosers.map((m,i) => `<tr style="background:${i%2===0?"#f8fafc":"#fff"};"><td style="padding:6px 10px;font-size:12px;font-weight:600;color:#333;border-bottom:1px solid #e4e8ed;">${m.ticker}</td><td style="padding:6px 10px;font-size:12px;font-weight:700;color:#c0392b;text-align:right;border-bottom:1px solid #e4e8ed;">${m.chgPct}%</td><td style="padding:6px 10px;font-size:12px;color:#555;border-bottom:1px solid #e4e8ed;">${m.comment||""}</td></tr>`).join("")}</table></td></tr>` : "";

  const tweets = s.sections.find(x=>x.key==="tweets")?.on && s.tweets?.length ? `<tr><td style="padding:0 32px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:14px;"><tr><td><div style="font-size:11px;font-weight:700;color:#fff;background:${B.blue};text-transform:uppercase;letter-spacing:1.5px;padding:5px 12px;display:inline-block;">Tweets / Market Noise</div></td></tr></table>${s.tweets.filter(t=>t.content).map(t => { const sentColor = t.sentiment==="Bullish"?"#27864a":t.sentiment==="Bearish"?"#c0392b":"#888"; const sentBg = t.sentiment==="Bullish"?"#e8f5e9":t.sentiment==="Bearish"?"#ffebee":"#f5f5f5"; return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:12px;border-bottom:1px solid #e4e8ed;padding-bottom:10px;"><tr><td><div style="margin-bottom:4px;">${t.sentiment ? `<span style="display:inline-block;background:${sentBg};color:${sentColor};font-size:10px;font-weight:700;padding:2px 8px;border-radius:3px;text-transform:uppercase;">${t.sentiment}</span> ` : ""}${t.impactType && t.impactValue ? `<span style="font-size:11px;color:#666;">${t.impactType}: ${t.impactValue}</span>` : ""}${t.time ? `<span style="font-size:10px;color:#999;margin-left:8px;">${t.time}</span>` : ""}</div><div style="font-size:13px;line-height:1.5;color:#333;margin-bottom:4px;">${nl2br(t.content)}</div>${t.link ? `<div style="margin-top:4px;"><a href="${t.link}" style="font-size:12px;color:${B.blue};">View post \u2192</a></div>` : ""}</td></tr></table>`; }).join("")}</td></tr>` : "";

  const bcra = s.sections.find(x=>x.key==="bcra")?.on && s.bcraData ? (() => { const hidden = s.bcraHiddenRows || {}; const entries = Object.entries(s.bcraData).filter(([k]) => !hidden[k]); if (!entries.length) return ""; return `<tr><td style="padding:0 32px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:14px;"><tr><td><div style="font-size:11px;font-weight:700;color:#fff;background:${B.blue};text-transform:uppercase;letter-spacing:1.5px;padding:5px 12px;display:inline-block;">BCRA Dashboard</div></td></tr></table><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border:1px solid #dde3ea;margin-bottom:16px;"><tr style="background:${B.navy};"><td style="padding:6px 10px;font-size:11px;font-weight:700;color:#fff;">Indicator</td><td style="padding:6px 10px;font-size:11px;font-weight:700;color:#fff;text-align:center;">Value</td></tr>${entries.map(([k,v],i) => `<tr style="background:${i%2===0?"#f8fafc":"#fff"};"><td style="padding:6px 10px;font-size:12px;font-weight:600;color:#333;border-bottom:1px solid #e4e8ed;">${k}</td><td style="padding:6px 10px;font-size:12px;color:#333;text-align:center;border-bottom:1px solid #e4e8ed;">${v}</td></tr>`).join("")}</table></td></tr>`; })() : "";

  const events = s.sections.find(x=>x.key==="events")?.on && s.events?.length ? `<tr><td style="padding:0 32px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:14px;"><tr><td><div style="font-size:11px;font-weight:700;color:#fff;background:${B.blue};text-transform:uppercase;letter-spacing:1.5px;padding:5px 12px;display:inline-block;">Events</div></td></tr></table><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border:1px solid #dde3ea;margin-bottom:16px;"><tr style="background:${B.navy};"><td style="padding:6px 10px;font-size:11px;font-weight:700;color:#fff;">Event</td><td style="padding:6px 10px;font-size:11px;font-weight:700;color:#fff;text-align:center;">Date</td><td style="padding:6px 10px;font-size:11px;font-weight:700;color:#fff;text-align:center;">ET</td><td style="padding:6px 10px;font-size:11px;font-weight:700;color:#fff;text-align:center;">BUE</td><td style="padding:6px 10px;font-size:11px;font-weight:700;color:#fff;text-align:center;">LON</td></tr>${s.events.filter(e=>e.title).map((e,i) => `<tr style="background:${i%2===0?"#f8fafc":"#fff"};"><td style="padding:6px 10px;font-size:12px;color:#333;border-bottom:1px solid #e4e8ed;">${e.title}</td><td style="padding:6px 10px;font-size:12px;color:#333;text-align:center;border-bottom:1px solid #e4e8ed;">${e.date ? fmtEventDate(e.date) : ""}</td><td style="padding:6px 10px;font-size:12px;color:#333;text-align:center;border-bottom:1px solid #e4e8ed;">${e.timeET ? fmtTime(e.timeET) : ""}</td><td style="padding:6px 10px;font-size:12px;color:#333;text-align:center;border-bottom:1px solid #e4e8ed;">${e.timeBUE ? fmtTime(e.timeBUE) : ""}</td><td style="padding:6px 10px;font-size:12px;color:#333;text-align:center;border-bottom:1px solid #e4e8ed;">${e.timeLON ? fmtTime(e.timeLON) : ""}</td></tr>`).join("")}</table></td></tr>` : "";

  const keyEvents = s.sections.find(x=>x.key==="keyEvents")?.on && s.keyEvents?.length ? `<tr><td style="padding:0 32px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:14px;"><tr><td><div style="font-size:11px;font-weight:700;color:#fff;background:${B.blue};text-transform:uppercase;letter-spacing:1.5px;padding:5px 12px;display:inline-block;">Key Events</div></td></tr></table><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:16px;border-bottom:1px solid #e4e8ed;padding-bottom:12px;">${s.keyEvents.filter(e=>e.event).map(e => `<tr><td style="padding:4px 0;"><span style="font-size:12px;font-weight:600;color:${B.navy};margin-right:8px;">${e.date ? fmtEventDate(e.date) : ""}</span><span style="font-size:13px;color:#333;">${e.event}</span></td></tr>`).join("")}</table></td></tr>` : "";

  const chart = s.sections.find(x=>x.key==="chart")?.on && s.chartImage?.base64 ? `<tr><td style="padding:0 32px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:14px;"><tr><td><div style="font-size:11px;font-weight:700;color:#fff;background:${B.blue};text-transform:uppercase;letter-spacing:1.5px;padding:5px 12px;display:inline-block;">Chart of the Day</div></td></tr></table><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:16px;border-bottom:1px solid #e4e8ed;padding-bottom:12px;"><tr><td>${s.chartImage.title ? `<div style="font-size:12.5px;font-weight:700;color:${B.navy};margin-bottom:8px;">${s.chartImage.title}</div>` : ""}<img src="${s.chartImage.base64}" alt="${s.chartImage.title||"Chart"}" style="max-width:100%;height:auto;display:block;margin-bottom:8px;" />${s.chartImage.caption ? `<div style="font-size:11px;color:#666;font-style:italic;margin-top:4px;">${s.chartImage.caption}</div>` : ""}</td></tr></table></td></tr>` : "";

  // --- signatures ---

  const sig = s.signatures.map(x => `<div style="margin-bottom:8px;"><div style="font-size:13px;font-weight:700;color:${B.navy};">${x.name}</div><div style="font-size:12px;color:#666;">${x.role}</div><div style="font-size:12px;color:${B.blue};">${x.email}</div></div>`).join("");

  // --- full template ---

  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Argentina Daily</title></head><body style="margin:0;padding:0;background:#f0f2f5;font-family:'Segoe UI',Calibri,Arial,sans-serif;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#f0f2f5;"><tr><td align="center" style="padding:20px 10px;"><table role="presentation" width="680" cellpadding="0" cellspacing="0" border="0" style="max-width:680px;width:100%;background:#fff;"><tr><td style="background:${B.navy};padding:24px 32px 20px;border-bottom:3px solid ${B.sky};"><img src="${getLogoWhiteB64()}" alt="Latin Securities" style="height:36px;display:block;" /><div style="font-size:10px;letter-spacing:1.5px;text-transform:uppercase;color:${B.sky};margin-top:4px;">Sales &amp; Trading</div><div style="font-size:20px;font-weight:600;color:#fff;margin-top:14px;">Argentina Daily</div><div style="font-size:12px;color:#8aa8d4;margin-top:2px;">${formatDate(s.date)}</div></td></tr>${s.summaryBar ? `<tr><td style="background:${B.lightBg};border-left:4px solid ${B.blue};padding:14px 24px;font-size:13.5px;line-height:1.55;color:${B.navy};"><strong>Today:</strong> ${s.summaryBar}</td></tr>` : ""}<tr><td style="padding:22px 0 0;"></td></tr>${s.sections.filter(x=>x.on).map(x => ({macro,tradeIdeas:trade,flows:flow,macroEstimates:mEst,corporate:corp,research,topMovers,tweets,bcra,events,keyEvents,chart})[x.key]||"").join("")}<tr><td style="padding:12px 32px 0;border-top:1px solid #e4e8ed;"><img src="${getLogoOrigB64()}" alt="Latin Securities" style="height:30px;display:block;margin-bottom:10px;" />${sig}</td></tr><tr><td style="padding:16px 0 0;"></td></tr><tr><td style="background:${B.navy};padding:14px 24px;border-top:2px solid ${B.sky};"><div style="font-size:10px;font-weight:700;color:${B.sky};margin-bottom:4px;">LATIN SECURITIES S.A.</div><div style="font-size:9px;color:#8aa8d4;line-height:1.5;">Arenales 707, 6th Floor · Buenos Aires, Argentina · www.latinsecurities.com.ar<br><br>This material is for informational purposes only and does not constitute an offer to buy or sell any financial instrument. © 2026 Latin Securities S.A.</div></td></tr></table></td></tr></table></body></html>`;
}
